name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger pipeline on push to master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust Node.js version as needed

      - name: Install dependencies
        run: |
          cd /home/divya/testaction/node_todo_cicd_master
          npm ci

      - name: Build and Deploy
        run: |
          cd /home/divya/testaction/node_todo_cicd_master
          npm run build  # Replace with your build command
          npm run deploy  # Replace with your deployment command

      - name: SSH into VM and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/divya/testaction/node_todo_cicd_master
            git pull origin master
            npm run restart  # Adjust for your application's restart command
