name: Deploy to GCP VM

on:
  push:
    branches:
      - master  # Trigger deployment on push to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust Node.js version as needed

      - name: Install dependencies
        run: |
          cd /home/divya/testaction/node_todo_cicd_master
          npm install  # Or use yarn if preferred

      - name: SSH into VM and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/divya/testaction/node_todo_cicd_master
            git pull origin master
            npm run restart  # Adjust for your application's restart command
