name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd /home/divya/testaction/node_todo_cicd_master
        npm install

    - name: Run tests
      run: |
        cd /home/divya/testaction/node_todo_cicd_master
        npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug directory existence
      run: |
        ls -la /home/divya/testaction/
        ls -la /home/divya/testaction/node_todo_cicd_master

    - name: Deploy to GCP VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Starting deployment..."
          cd /home/divya/testaction/node_todo_cicd_master
          pwd
          ls -la
          git pull origin master
          npm install
          pm2 restart node_todo_app || pm2 start app.js --name node_todo_app
          echo "Deployment completed."
