name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger pipeline on push to master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust Node.js version as needed

      - name: Ensure directory exists
        run: |
          sudo mkdir -p /home/divya/testaction/node_todo_cicd_master

      - name: Install dependencies and build
        run: |
          cd /home/divya/testaction/node_todo_cicd_master || { echo "Directory not found"; exit 1; }
          npm ci  # Install dependencies
          npm run build  # Build your application

      - name: Deploy and Restart Application
        run: |
          cd /home/divya/testaction/node_todo_cicd_master || { echo "Directory not found"; exit 1; }
          npm run deploy  # Deploy your application
          npm run restart  # Restart your application

      - name: SSH into VM and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/divya/testaction/node_todo_cicd_master
            git pull origin master
            npm run restart  # Restart your application
